website/models.py
from .import db
from flask_login import UserMixin
from website import db

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email=db.Column(db.String(150),unique=True)
    password=db.Column(db.String(150))
    meals = db.relationship('Meal', backref='user', lazy=True)
    symptoms = db.relationship('Symptom', backref='user', lazy=True)

class Meal(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    meal_name = db.Column(db.String(100), nullable=False)
    meal_datetime = db.Column(db.DateTime, nullable=False)

class Symptom(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    symptom_name = db.Column(db.String(100), nullable=False)
    symptom_datetime = db.Column(db.DateTime, nullable=False)
    severity_level = db.Column(db.Integer, nullable=False)
    
class CombinedData(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    meal_name = db.Column(db.String(100), nullable=False)
    symptom_name = db.Column(db.String(100), nullable=False)


    

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
db=SQLAlchemy()
DB_NAME="HealthQuotient.db"
def create_app():
    app=Flask(__name__)
    app.config['SECRET_KEY']='jhfsjhfg hjagfhagdf'
    app.config['SQLALCHEMY_DATABASE_URI']=f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False
    db.init_app(app)
   

        

    from .views import views
    from .auth import auth
    
    app.register_blueprint(views,url_prefix='/')
    app.register_blueprint(auth,url_prefix='/')

    from .models import User, Meal, Symptom
    with app.app_context():
        db.create_all()
        login_manager=LoginManager()
        login_manager.login_view='auth.login'
        login_manager.init_app(app)
    
        @login_manager.user_loader
        def load_user(id):
            return User.query.get(int(id))
    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint,render_template,request,flash,redirect,url_for,jsonify
from .models import User,Meal,Symptom,db,CombinedData
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import login_user,login_required,logout_user,current_user
from website import db
from mlxtend.frequent_patterns import fpgrowth,association_rules

auth=Blueprint('auth',__name__)





@auth.route('/login',methods=['GET','POST'])
def login():
    if request.method=='POST':
        email=request.form.get('email')
        password=request.form.get('password')
        user=User.query.filter_by(email=email).first()
        joined_table_data = db.session.query(Meal.meal_name, Symptom.symptom_name) \
        .join(Symptom, Meal.user_id == Symptom.user_id).all()
        print(joined_table_data)
        if user:
            if check_password_hash(user.password,password):
                flash('Logged in suucessfully',category='success')
                login_user(user,remember=True)
                return render_template('title.html')
            else:
                flash('incoorect password or email',category='error')
        
    return render_template("login.html")


@auth.route('/signup',methods=['GET','POST'])
def signup():
    if request.method=='POST':
        email=request.form.get('email')
        username=request.form.get('username')
        password=request.form.get('password')
        
        user=User.query.filter_by(email=email).first()
        if user:
            flash("user already exits",category='error')

        if len(email)<4:
            flash("email must be greater than 4 char",category='error')
        elif len(username)<2:
            flash("username must be greater than 2 char",category='error')

        elif len(password)<7:
            flash("security issue with ur pass",category='error')

        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password, method='scrypt'))
            db.session.add(new_user)
            db.session.commit()
            login_user(user,remember=True)
            flash("account created",category='success')
            return redirect(url_for('views.home'))
            
    return render_template("signup.html")
    
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

        

website/views.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from .models import db
from mlxtend.frequent_patterns import fpgrowth,association_rules
import csv
from sqlalchemy import join
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
import plotly.express as px
from website import DB_NAME
from .models import Meal, Symptom, db, CombinedData,User

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("base.html", user=current_user)

@views.route('/title')
@login_required
def title():
    return render_template('title.html', user=current_user)

@views.route('/add_meal', methods=['POST'])
@login_required
def add_meal():
    if request.method == 'POST':
        meal_name = request.form.get('inputmeal')
        meal_date = request.form.get('inputDate')
        meal_time = request.form.get('inputTime')
        
        meal_datetime = datetime.strptime(meal_date + ' ' + meal_time, '%Y-%m-%d %H:%M')
        
        new_meal = Meal(user=current_user, meal_name=meal_name, meal_datetime=meal_datetime)
        db.session.add(new_meal)
        db.session.commit()

    return redirect(url_for('views.title'))

@views.route('/add_symptom', methods=['POST'])
@login_required
def add_symptom():
    if request.method == 'POST':
        symptom_name = request.form.get('inputsymptom')
        symptom_date = request.form.get('inputdate')
        symptom_time = request.form.get('inputtime')
        
        symptom_datetime = datetime.strptime(symptom_date + ' ' + symptom_time, '%Y-%m-%d %H:%M')
        
        new_symptom = Symptom(user=current_user, symptom_name=symptom_name, symptom_datetime=symptom_datetime, severity_level=1)
        db.session.add(new_symptom)
        db.session.commit()
        

    return redirect(url_for('views.title'))




@views.route('/frequent_patterns')
def frequent_patterns():
    meal_count = Meal.query.filter_by(user_id=current_user.id).count()
    symptom_count = Symptom.query.filter_by(user_id=current_user.id).count()
    
    if meal_count < 10 or symptom_count < 10:
        return render_template('title.html', user=current_user)
    
    joined_table_data = db.session.query(Meal.meal_name, Symptom.symptom_name) \
        .join(Symptom, Meal.user_id == Symptom.user_id).all()
    
    csv_file_path = 'joined_table_data.csv'

    with open(csv_file_path, mode='w', newline='') as csv_file:
        csv_writer = csv.writer(csv_file)
        csv_writer.writerow(['Meal Name', 'Symptom Name'])
        for row in joined_table_data:
            csv_writer.writerow([row.meal_name, row.symptom_name])

    data = pd.read_csv(csv_file_path)
    
    transaction = []
    for i in range(data.shape[0]):
        transaction.append([str(data.values[i, j]) for j in range(data.shape[1])])

    transaction_np = np.array(transaction)
    transaction_np[transaction_np == 'True'] = '1'
    transaction_np[transaction_np == 'False'] = '0'
    
    te = TransactionEncoder()
    te_ary = te.fit(transaction_np).transform(transaction_np)
    data_encoded = pd.DataFrame(te_ary, columns=te.columns_)
    
    res = fpgrowth(data_encoded, min_support=0.05, use_colnames=True)
    res = association_rules(res, metric="lift", min_threshold=1)
    
    
    res = res.sort_values("confidence", ascending=False)
    
    return render_template('frequent_patterns.html', rules=res)

website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="styles.css" />
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Health Quotient</title>
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&family=Quicksand&family=Raleway:wght@200;300;400;600;700&display=swap');
*{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
    font-family: 'Quicksand', sans-serif;
    font-family: 'Raleway', sans-serif;
    list-style: none;
    text-decoration: none;
    scroll-behavior: smooth;
}


header{
    position: fixed;
    width: 100%;
    right: 0;
    top: 0;
    display: flex;
    align-items:left;
    justify-content: space-between;
    z-index: 111;
    padding: 20px 320px;
    background:linear-gradient(rgb(0, 153, 0),rgb(0, 153, 0),rgb(0, 153, 0));
     ;
    box-shadow: rgba(104, 226, 192, 0.1) 0px 10px 10px -10px;
    
}

.logo{
    font-size: 2.4rem;
    color: #64a200;
}
    .navlist{
display: flex;
}
.navlist a {
    color: #04a44c;
    font-size: 1.2rem;
    font-weight: 400;
    padding: 15px 20px;
    transition: color .3s;
    text-decoration: none !important; /* Add this line to remove underline */
}

h1{
    margin-left: -200px;
    color: #ffffff;
    font-size: 3.4rem;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
}

.button {
    display: inline-block;
    padding: 10px 20px;
    font-size: 16px;
     background-image: linear-gradient(90deg, #ffffff , #ffffff );
    
    color: white;
    border: none;
    border-radius: 30px;
    cursor: pointer;
    margin-left: 55px; 
    transition: background-color 0.3s ease-in-out;
  }
  .button:hover {
    /* Keep the same background image */
    background-image: linear-gradient(90deg, #64a200 0%, #0fdf6d 100%);
    /* Change the text color on hover */
    color:rgb(172, 227, 237); /* Change this to the desired text color */
}

#menu-icon{
font-size: 3rem;
cursor: pointer;
display: none;
}
section{
padding: 85px 17%;
}
body {
    background-image: url('medical.png');
    background-size: cover; /* You can adjust this property to control how the image covers the background */
    background-repeat: no-repeat; /* Prevent the background image from repeating */
    background-attachment: fixed;
}


</style>
  <body>
    <header>
        
        <h1>Health Quotient </h1>
        <div class="bx bx-menu" id="menu-icon"><i class="uil uil-list-ul"></i></div>
        <ul class="navlist">
            
            <a href="/login" class="button">Sign In</a>
            <a href="/signup" class="button button-secondary">Join Now</a>
    
        </ul>
    </header>
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

website/templates/frequent_patterns.html
<!DOCTYPE html>
<html>
<head>
    <title>Frequent Patterns</title>
</head>
<body>
    <h1>Frequent Patterns</h1>
    <table>
        <thead>
            <tr>
                <th>Antecedents</th>
                <th>Consequents</th>
                <th>Support</th>
                <th>Confidence</th>
                <th>Lift</th>
            </tr>
        </thead>
        <tbody>
            {% for rule in rules.iterrows() %}
                <tr>
                    <td>{{ rule[1]['antecedents'] }}</td>
                    <td>{{ rule[1]['consequents'] }}</td>
                    <td>{{ rule[1]['support'] }}</td>
                    <td>{{ rule[1]['confidence'] }}</td>
                    <td>{{ rule[1]['lift'] }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

website/templates/signup.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>health Quotient!</title>
</head>
<body>
<div class="container overflow-hidden text-ce<!doctype html>
    <html lang="en">
      <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
        <title>HealthQuotient</title>
      </head>
      <body>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&family=Quicksand&family=Raleway:wght@200;300;400;600;700&display=swap');
        *{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
            font-family: 'Quicksand', sans-serif;
            font-family: 'Raleway', sans-serif;
            list-style: none;
            text-decoration: none;
            scroll-behavior: smooth;
        }
        
        
        header{
            position: fixed;
            width: 100%;
            right: 0;
            top: 0;
            display: flex;
            align-items:left;
            justify-content: space-between;
            z-index: 111;
            padding: 20px 320px;
            background:linear-gradient(rgb(0, 153, 0),rgb(0, 153, 0),rgb(0, 153, 0));
             ;
            box-shadow: rgba(104, 226, 192, 0.1) 0px 10px 10px -10px;
            
        }
        
        .logo{
            font-size: 2.4rem;
            color: #64a200;
        }
            .navlist{
        display: flex;
        }
        .navlist a {
            color: #04a44c;
            font-size: 1.2rem;
            font-weight: 400;
            padding: 15px 20px;
            transition: color .3s;
            text-decoration: none !important; /* Add this line to remove underline */
        }
        
        h1{
            margin-left: -200px;
            color: #ffffff;
            font-size: 3.4rem;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }
        
        .button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
             background-image: linear-gradient(90deg, #ffffff , #ffffff );
            
            color: white;
            border: none;
            border-radius: 30px;
            cursor: pointer;
            margin-left: 55px; 
            transition: background-color 0.3s ease-in-out;
          }
          .button:hover {
            /* Keep the same background image */
            background-image: linear-gradient(90deg, #64a200 0%, #0fdf6d 100%);
            /* Change the text color on hover */
            color:rgb(172, 227, 237); /* Change this to the desired text color */
        }
        
        #menu-icon{
        font-size: 3rem;
        cursor: pointer;
        display: none;
        }
        section{
        padding: 85px 17%;
        }
        body {
            background-image: url('medical.png');
            background-size: cover; /* You can adjust this property to control how the image covers the background */
            background-repeat: no-repeat; /* Prevent the background image from repeating */
            background-attachment: fixed;
        }
        
        
        </style>
        <header>
            
            <h1>Health Quotient </h1>
            <div class="bx bx-menu" id="menu-icon"><i class="uil uil-list-ul"></i></div>
            <ul class="navlist">
                
                
                <a href="#" class="button button-secondary">Join Now</a>
        
            </ul>
        </header>
        
        <!-- Section: Design Block -->
    <section class="">
        <!-- Jumbotron -->
        <div class="px-4 py-5 px-md-5 text-center text-lg-start" style="background-color:#ffffff">
          <div class="container">
            <div class="row gx-lg-5 align-items-center">
              <div class="col-lg-6 mb-5 mb-lg-0">
                <h1 class="my-5 display-3 fw-bold ls-tight">
                  Health is wealth  <br />
                  <span class="text-primary"> A healthy outside starts from the inside</span>
                  
                </h1>
                <p style="margin-left: -50%;"> By analyzing user-reported data, we decipher the complex interplay between diet and well-being, delivering insightful results that pinpoint the foods responsible for triggering various symptoms. This innovative approach empowers individuals to make informed decisions about their diets, fostering a proactive approach to managing their health.</p>
              </div>
      
              <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="card">
                  <div class="card-body py-5 px-md-5">
                    <form>
                      <!-- 2 column grid layout with text inputs for the first and last names -->
                      <div class="row">
                        
                          <div class="form-outline mb-4">
                            <input type="text" id="form3Example1" class="form-control" />
                            <label class="form-label" for="form3Example1">User name</label>
                         
                        </div>
                       
                      </div>
      
                      <!-- Email input -->
                      <div class="form-outline mb-4">
                        <input type="email" id="form3Example3" class="form-control" />
                        <label class="form-label" for="form3Example3">Email address</label>
                      </div>
      
                      <!-- Password input -->
                      <div class="form-outline mb-4">
                        <input type="password" id="form3Example4" class="form-control" />
                        <label class="form-label" for="form3Example4">Password</label>
                      </div>
                      
                      <!-- Password input -->
                      <div class="form-outline mb-4">
                        <input type="password" id="form3Example4" class="form-control" />
                        <label class="form-label" for="form3Example4">Confirm Password</label>
                      </div>
                      
      
                      <!-- Submit button -->
                      <button type="submit" style="background-color: rgb(0,153,0) ;"   class="btn btn-primary btn-block mb-4">
                        Sign up
                      </button>
      
                      <!-- Register buttons -->
                      <div class="text-center">
                        
                        <button type="button" class="btn btn-link btn-floating mx-1">
                          <i class="fab fa-facebook-f"></i>
                        </button>
      
                        <button type="button" class="btn btn-link btn-floating mx-1">
                          <i class="fab fa-google"></i>
                        </button>
      
                        <button type="button" class="btn btn-link btn-floating mx-1">
                          <i class="fab fa-twitter"></i>
                        </button>
      
                        <button type="button" class="btn btn-link btn-floating mx-1">
                          <i class="fab fa-github"></i>
                        </button>
                      </div>
                    </form>
                  </div>
                </div
              </div>
            </div>
          </div>
        </div>
        <!-- Jumbotron -->
      </section>
      <!-- Section: Design Block -->
        
    
        <!-- Optional JavaScript; choose one of the two! -->
    
        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        -->
      </body>
    </html>nter">
    <div class="row gx-5">
        <div class="col">
            <div class="p-3">
                <!-- Display Flash Messages for Errors -->
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <ul class="flashes">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% endwith %}

                <form class="form-signin" method="POST" action="{{ url_for('auth.signup') }}">
                    <h1 class="h3 mb-3 font-weight-normal">Sign up</h1>
                    <label for="inputUsername" class="sr-only">Username</label>
                    <input type="text" id="inputUsername" class="form-control" name="username" placeholder="Username" required autofocus>
                    <label for="inputEmail" class="sr-only">Email address</label>
                    <input type="email" id="inputEmail" class="form-control" name="email" placeholder="Email address" required>
                    <label for="inputPassword" class="sr-only">Password</label>
                    <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Password" required>
                    <label for="inputPasswordConfirm" class="sr-only">Confirm Password</label>
                    <input type="password" id="inputPasswordConfirm" class="form-control" name="password_confirm" placeholder="Confirm Password" required>
                    <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" value="remember-me"> Remember me
                        </label>
                    </div>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
<!--
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>
</html>